baseurl = "https://runc.io"
languageCode = "en-us"
title = "Open Container Project"
author = "Patrick Chanezon"
copyright = "Copyright (c) 2015, Linux Foundation"
canonifyurls = true
paginate = 3

# Needed by Theme demos in exampleSite.
[params]
  DateForm = "Mon, Jan 2, 2006"
  github = "opencontainers/runc" # optional
  headerCover = "images/ocf_background_144.png" # optional
#  footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "UA-64352818-2" # optional
